[package]
name = "casper-exchange-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
web-dashboard-common = { path = "../web-dashboard-common" }
casper-event-consumer = { path = "../casper-event-consumer" }
anyhow = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
