[package]
name = "odra-contracts"
version = "0.1.0"
edition = "2024"

[dependencies]
odra = "2.5.0"
odra-modules = "2.5.0"
odra-casper-livenet-env = "2.5.0"
serde_json = "1"

[[bin]]
name = "deploy"
path = "bin/deploy.rs"
test = false

[[bin]]
name = "simulator"
path = "bin/simulator.rs"
test = false