[package]
name = "web-whale-activity"
version = "0.1.0"
edition = "2024"

[dependencies]
web-dashboard-common = { path = "../web-dashboard-common" }
casper-event-consumer = { path = "../casper-event-consumer" }
anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
